name: HW1-test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-latest", "macos-latest", "windows-latest"]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install Dependencies
              run: | 
                python -m pip install --upgrade pip
                pip install pytest

            - name: Test with PyTest
              run: |
                pytest
